### ISSUE TITLE
Specific title for each page

### ISSUE THREAD

**Issue by ghost** [braceio/tags#9]
How do you guys solve the problem that each HTML page should have a specific title? With CodeKit's Kit language, I use a "title" variable for this, that gets used in the "site-head" partial, e.g., each site's page starts with something like:

```
<!-- $title = My Post's Title -->

<!-- @import site-head.kit -->

<!-- ... page's specific code after ... -->
```

Is there a simple solution for this in Brace Tags?

Thank you.

**Comment by colevscode** [comment]
There's a solution, but you'll need to add a custom tags. For example you could do something like this:

_in tags/tags.py_

```
@lang.add_tag
def include_with_title(path, title, context={}):
    '''
    Renders the content of a file, adding a title variable to the context. 
    '''
    context.update(title=title)
    return include(path, context)


@lang.add_tag
def title(context={}):
    '''
    Renders the title variable from the current context. 
    '''
    return context.get('title')
```

(I haven't tried implementing this in tags yet, so sorry for typos)

Then you'd use it in your html like so:

_myfile.html_

```
{% include_with_title _partials/header.html "My file!" %}
<body> ... </body>
```

__partials/header.html_

```
<head>
    <title>{% title %}</title>
</head>
```

**Comment by colevscode** [comment]
Copied this to the wiki.
